### ISSUE TITLE
should there be a field in EpiduralRequest for Indication?

### ISSUE THREAD

**Issue by pacharanero** [Epidurio/opal-epidur.io#1]
Should there be a field in [EpiduralRequest](https://github.com/Epidurio/opal-epidur.io/blob/17c178b344c31a1b566289f8aef58a5357602fdd/epidurio/models.py#L31) for Indication? It's not currently in the Ruby version, but it would seem to be a reasonable thing to want to know and useful for audit?

One for discussion.

The vast majority would be for `Labour Analgesia`. Maybe that's the only real indication in this context. Maybe that's why it's not in the Ruby version as it's not necessary.

**Comment by pacharanero** [comment]
actually, there is a field for this in the EpiduralInsertion record.

is it better there or here do we think?

**Comment by timcknowles** [comment]
Likely midwifes are only going to be requesting an Epidural for labour analgesia (there are niche other requests I can think of e.g. PCA where regional is known by them to be contraindicated, or Epidurals on 'obstetric request' ) but that's probs not for the MVP. 

The reason the indication is in the insertion record was to handle anaesthetists documenting the indication of a procedure more likely done in theatre. e.g. a trial, repair of a tear, elective section, emergency section. In this case there may not be a midwife request. Also to handle just doing an epidural for labour analgesia in the absence of a request (e.g. if the staff or department don't want to enforce or buy into the request part of the workflow)

**Comment by pacharanero** [comment]
Let's leave Indication in the Insertion record then.

closed
