### ISSUE TITLE
convert OUTCOME_CHOICES to a SNOMED-CT LookupList

### ISSUE THREAD

**Issue by pacharanero** [Epidurio/opal-epidur.io#2]
for expediency the first draft of EpiduralInsertion has used django Choices for pick-lists, however Opal provides a nicer way to do this using [ForeignKeyOrFreeText(LookupList)](http://opal.openhealthcare.org.uk/docs/guides/referencedata/#reference-data)

ideally all picklists should use a SNOMED-CT lookuplist in this way

**Comment by timcknowles** [comment]
You mean like this for an IV line.
869511000000103 |Peripheral intravenous cannula (physical object)|

**Comment by pacharanero** [comment]
Absolutely.

SNOMED is widely recognised as a good international standard (even if it is essentially proprietary)
Using clinical terminology reduces the need for having to go into maddening and often unhelpful levels of detail in data models.

**Comment by pacharanero** [comment]
closing as we are no longer using OUTCOME_CHOICES at all
