### ISSUE TITLE
'Request Epidural' should only show if the patient has not already had a request made

### ISSUE THREAD

**Issue by pacharanero** [Epidurio/opal-epidur.io#20]
If the patient has already had an epidural request made then there's no need to show this button

It would be helpful to see that a request has been made though, and maybe the date and time of this request.

**Comment by timcknowles** [comment]
yes agree and there should be a visual notification of status instead e.g has an epidural requested, has an epidural

**Comment by pacharanero** [comment]
@fredkingham I've implemented the conditional Angular logic that's required in branch https://github.com/Epidurio/opal-epidur.io/tree/20-request-epidural-should-only-show-if-the-patient-has-not-already-had-a-request-made It doesn't automatically update after the RequestEpidural Pathway is complete though. It updates if you refresh the page.

**Comment by pacharanero** [comment]
the opal code that fixes the automatic updating has been merged https://github.com/openhealthcare/opal/pull/1415

which means we can close this as done via #21
