### ISSUE TITLE
It feels as though the Epidural Follow-Up form should have a free text box for any comments

### ISSUE THREAD

**Issue by pacharanero** [Epidurio/opal-epidur.io#31]

**Comment by pacharanero** [comment]
@timcknowles what do you think?

**Comment by timcknowles** [comment]
@pacharanero  completely agree. The follow up form and the request form need clinical review and sense checking. They were just knocked up to get us of the ground. I will work on this attempting to merge best practice and national guidance is it exists. The insertion record is in a better state but also has some minor bugs e.g. diff units needed for diff drugs.
