### ISSUE TITLE
application colour scheme needs changing

### ISSUE THREAD

**Issue by pacharanero** [Epidurio/opal-epidur.io#33]
@timcknowles suggested invoking some nice homely Obstetric Anaesthesia Association vibes by using their colours (or similar ones), which sounds like a decent place to start.

![image](https://user-images.githubusercontent.com/2348385/36541258-3f6c0c12-17d5-11e8-917b-e371e158b17d.png)

**Comment by pacharanero** [comment]
dark blue #0084FF
light blue #0084FF
grey #EEEEEE

**Comment by pacharanero** [comment]
WIP merged https://github.com/Epidurio/opal-epidur.io/pull/34

**Comment by pacharanero** [comment]
needs further work and some collective review and documentation

**Comment by timcknowles** [comment]
I like this so far:

A few things:

- loading splash (still green)
- button hover (?brown) suggest blue or purple/pink. Or align with record epidural button hover
- in mobile view top and bottom are green still

**Comment by pacharanero** [comment]
@timcknowles those are now fixed I think
